### ISSUE TITLE
Installation issue - syntax error

### ISSUE THREAD

**Issue by tbar** [Vassius/ttrss-python#10]
I get the following error when installing:

Extracting ttrss_python-0.4-py3.2.egg to c:\python32\lib\site-packages
  File "c:\python32\lib\site-packages\ttrss_python-0.4-py3.2.egg\ttrss\client.py", line 89
    if c['id'] == u'subscribed-feeds':
                                    ^
SyntaxError: invalid syntax

If I change:
  if c['id'] == u'subscribed-feeds':
to:
  if c['id'] == 'subscribed-feeds':

Then installation proceeds without errors. I'm using python32 on Windows.

(BTW: pip package isn't updated to latest source available)

**Comment by Vassius** [comment]
Fixed in pull request #11

**Comment by Vassius** [comment]
pip package is now updated to latest source, version 0.5
